### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [bem-site/broken-links-checker#1]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by tormozz48** [comment]
@h13i32maru Thank you.
I have tried to use your service and it's awesome!

It is simple and straight way to avoid gh pages usage
